# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Custom bindings
bind -n C-q set-window-option synchronize-panes

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

######################
### DESIGN CHANGES ###
######################

# panes
set -g pane-border-style 'fg=colour17 bg=colour0'
set -g pane-active-border-style 'fg=colour172 bg=colour0'

# status bar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=colour172 bg=colour17'

# messages
set -g message-style 'fg=colour17 bg=colour172'

# color support
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# window and pane titles
setw -g automatic-rename
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

######################
# DESIGN CHANGES END #
######################


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
