#!/usr/bin/env bash
set -euxo pipefail

INFO() {
    /bin/echo -e "\e[104m\e[97m[INFO]\e[49m\e[39m ${*}"
}
WARNING() {
    /bin/echo >&2 -e "\e[101m\e[97m[WARNING]\e[49m\e[39m ${*}"
}
ERROR() {
    /bin/echo >&2 -e "\e[101m\e[97m[ERROR]\e[49m\e[39m ${*}"
}

getOhMyBash() {
    if [ ! -d "${HOME}/.oh-my-bash" ]; then
        INFO "Installing Oh-My-Bash"
        curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh | bash
    fi
}
compileGoTools() {
    INFO "Compiling cheatsheet"
    go install github.com/cheat/cheat/cmd/cheat@latest
    INFO "Compiling k9s"
    go install github.com/derailed/k9s@latest
    INFO "Compiling yq"
    go install github.com/mikefarah/yq/v4@latest
}
getTPM() {
    mkdir -p ~/.tmux/plugins
    if [ ! -d ~/.tmux/plugins/tpm ]; then
        INFO "Installing tmux plugin manager"
        git clone https://github.com/tmux-plugins/tpm "${HOME}"/.tmux/plugins/tpm
    fi
}
setupKeysSSH() {
    INFO "Setting up SSH keys"
    USER_EMAIL="krcdotbrk@gmail.com"
    ssh-keygen -t ed25519 -C "${USER_EMAIL}" -f "${HOME}"/.ssh/id_ed25519 -q -N ""
    PUB_KEY=$(cat "${HOME}"/.ssh/id_ed25519.pub)
    PUB_KEY_SHORT=$(echo "${PUB_KEY}" | awk  '{print $1,$2}')
    git config --global user.signingkey "${PUB_KEY}"
    if [ -f "${HOME}"/.config/git/allowed_signers ]; then
        rm "${HOME}"/.config/git/allowed_signers
    fi
    printf '%s namespaces="git" %s' "${USER_EMAIL}" "${PUB_KEY_SHORT}" | tee -a "${HOME}"/.config/git/allowed_signers &>/dev/null
}

getOhMyBash
compileGoTools
getTPM
setupKeysSSH
yadm checkout "${HOME}"