#!/usr/bin/env bash

# logging functions
INFO() {
	/bin/echo -e "\e[104m\e[97m[INFO]\e[49m\e[39m ${*}"
}

WARNING() {
	/bin/echo >&2 -e "\e[101m\e[97m[WARNING]\e[49m\e[39m ${*}"
}

ERROR() {
	/bin/echo >&2 -e "\e[101m\e[97m[ERROR]\e[49m\e[39m ${*}"
}

main() {
    USERID="$(id -u)"
    # verify root status
	if [ ! "$USERID" = "0" ]; then
		ERROR "This bootstrap script needs to be run as root."
		exit 1
	fi
    # dnf config
    if ! grep -qF "assumeyes" /etc/dnf/dnf.conf; then
		INFO "Configuring dnf."
        printf "max_parallel_downloads=16\nassumeyes=True\nfastestmirror=True" | tee -a /etc/dnf/dnf.conf
	fi
    # rpmfusion repos
    INFO "Setting up rpmfusion repos."
    dnf config-manager --set-enabled crb
    dnf install -y epel-release
    dnf install -y https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-"$(rpm -E %rhel)".noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-"$(rpm -E %rhel)".noarch.rpm
    dnf groupupdate core -y
    # flathub, gnome extensions
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    flatpak install org.gnome.Extensions -y
    # oh-my-bash
    if [ ! -d "$HOME/.oh-my-bash" ]; then
        INFO "Downloading oh-my-bash."
        curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh | bash
    fi
    # micro editor
    if [ ! -x "$(command -v micro)" ]; then
        INFO "Installing micro text editor."
        curl https://getmic.ro | bash && sudo mv ./micro /usr/bin
    fi
    # various
    dnf install -y gnome-tweaks gnome-shell-extension-workspace-indicator \
        bat \
        tmux \
        ncdu \
        golang \
        python3-pip
    # go packages
    go install github.com/cheat/cheat/cmd/cheat@latest
    # tmux plugins
    mkdir -p ~/.tmux/plugins
    if [ ! -d ~/.tmux/plugins/tpm ]; then
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    fi

    if [ -x ~/.tmux/plugins/tpm/bin/install_plugins ]; then
        ~/.tmux/plugins/tpm/bin/install_plugins
    fi

    if [ -x ~/.tmux/plugins/tpm/bin/update_plugins ]; then
        ~/.tmux/plugins/tpm/bin/update_plugins all
    fi
    # Install nerd fonts
    if [ ! -d "/usr/share/fonts/JetBrainsMono" ]; then
        INFO "Installing JetBrains Nerd Font."
        mkdir -p /usr/share/fonts/JetBrainsMono
        (cd /usr/share/fonts/JetBrainsMono && curl -fsSLo JetBrainsMonoNerdFontMono-Regular.ttf https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFontMono-Regular.ttf)
        fc-cache -fv /usr/share/fonts/JetBrainsMono
    fi
    # Check out all dotfiles
    yadm checkout .
    reboot
}

main