#!/usr/bin/env bash
set -euo pipefail

INFO() {
    /bin/echo -e "\e[104m\e[97m[INFO]\e[49m\e[39m ${*}"
}
WARNING() {
    /bin/echo >&2 -e "\e[101m\e[97m[WARNING]\e[49m\e[39m ${*}"
}
ERROR() {
    /bin/echo >&2 -e "\e[101m\e[97m[ERROR]\e[49m\e[39m ${*}"
}

getOhMyBash() {
    if [ ! -d "${HOME}/.oh-my-bash" ]; then
        INFO "Installing Oh-My-Bash"
        curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh | bash
    fi
}
compileGoTools() {
    INFO "Compiling cheatsheet"
    go install github.com/cheat/cheat/cmd/cheat@latest
    INFO "Compiling k9s"
    go install github.com/derailed/k9s@latest
    INFO "Compiling yq"
    go install github.com/mikefarah/yq/v4@latest
}
getTPM() {
    mkdir -p "${HOME}"/.tmux/plugins
    if [ ! -d "${HOME}/.tmux/plugins/tpm" ]; then
        INFO "Installing tmux plugin manager"
        git clone https://github.com/tmux-plugins/tpm "${HOME}"/.tmux/plugins/tpm
    fi
}
configNvim() {
    mkdir -p "${HOME}"/.config/nvim
    ln -s "${HOME}"/.vimrc "${HOME}"/.config/nvim/init.vim
    git clone https://github.com/VundleVim/Vundle.vim.git "${HOME}"/.vim/bundle/Vundle.vim
    nvim +PluginInstall +qall
}
yadmInit() {
    yadm checkout "${HOME}"
    yadm switch -c "local"
    yadm branch --set-upstream-to=origin/master
}
loadDconf() {
    if [ "${XDG_CURRENT_DESKTOP}" = "GNOME" ] && ! grep -qEi "(Microsoft|WSL)" /proc/sys/kernel/osrelease &> /dev/null ; then
        INFO "Restoring dconf db"
        dconf load / < "${HOME}"/.config/dconf/dconf.ini
    fi
}
confGnomeTerminal() {
    if [ "${XDG_CURRENT_DESKTOP}" = "GNOME" ] && ! grep -qEi "(Microsoft|WSL)" /proc/sys/kernel/osrelease &> /dev/null ; then
    GNOME_TERMINAL_PROFILE="$(gsettings get org.gnome.Terminal.ProfilesList default | sed s/\'//g)"
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:"${GNOME_TERMINAL_PROFILE}"/ palette "['rgb(10,10,10)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(245,245,245)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']"
    fi
}
setupKeysSSH() {
    INFO "Setting up SSH keys"
    USER_EMAIL="krcdotbrk@gmail.com"
    KEY_LOC="${HOME}"/.ssh/id_ed25519
    ssh-keygen -t ed25519 -C "${USER_EMAIL}" -f "${KEY_LOC}" -q -N ""
    PUB_KEY=$(cat "${KEY_LOC}".pub)
    PUB_KEY_SHORT=$(echo "${PUB_KEY}" | awk  '{print $1,$2}')
    git config --global user.signingkey "${PUB_KEY}"
    git config --global gpg.ssh.allowedSignersFile "${HOME}/.config/git/allowed_signers"
    if [ -f "${HOME}"/.config/git/allowed_signers ]; then
        rm "${HOME}"/.config/git/allowed_signers
    fi
    printf '%s namespaces="git" %s' "${USER_EMAIL}" "${PUB_KEY_SHORT}" | tee -a "${HOME}"/.config/git/allowed_signers &>/dev/null
}
yadmLocalKeys() {
    eval "$(ssh-agent -s)"
    ssh-add "${KEY_LOC}"
    yadm add "${HOME}"/.config/git/allowed_signers "${HOME}"/.gitconfig
    yadm commit -S -m "local: set up git signing with SSH keys"
}

getOhMyBash
compileGoTools
getTPM
configNvim
yadmInit
loadDconf
confGnomeTerminal
setupKeysSSH
yadmLocalKeys
INFO "Setup complete! Reboot recommended."