#!/usr/bin/env fish

function osctx
	# parse for -u or --unset
	argparse u/unset -- $argv
	# fail if args are given and they couldn't be parsed 
	or return

	# var auto-generated by argparse
	if set -q _flag_unset
			set -e OS_CLOUD
    	return 0
	end

	set -l clouds_entry (yq '.clouds | keys | .[]' ~/.config/openstack/clouds.yaml | fzf --height=~100% --style full \
		--border --padding 1,2 \
		--border-label ' ~/.config/openstack/clouds.yaml entries ' --input-label ' Search ')
	set -gx OS_CLOUD $clouds_entry
	echo "Switched to: $OS_CLOUD"
end
